### ISSUE TITLE
Exception: EMFILE: too many open files, open 'd:\Desktop\real project\smartyt\package.json'

### ISSUE THREAD

**Issue by Mdkamrujjamanshimu** [daidodo/format-imports-vscode#103]
## Code snippet triggering the exception

```ts
// INSERT CODE HERE
```

## All Logs

(Please open the output channel for "JS/TS Import/Export Sorter" and copy/paste ALL logs here)

```log
PASTE LOGS HERE
```

**Comment by daidodo** [comment]
@Mdkamrujjamanshimu 
Thanks for the feedback!

Could you provide more info about the issue, e.g. screenshots, demo project, logs, environment?
