### ISSUE TITLE
Is there a way to only sort subgroups?

### ISSUE THREAD

**Issue by paulflo150** [daidodo/format-imports-vscode#106]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Is there a way to only sort subgroups? My imports are all grouped in subgroups which are delimited by a blank line, and I would like to keep them as they are, but would of course like the ability to sort them.

**Comment by daidodo** [comment]
Could you elaborate your requirement, better with some examples?

Thanks!

**Comment by daidodo** [comment]
@paulflo150 
Thanks for you feedback!

Is it still a requirement for you? If no, I'll close the issue later.
