### ISSUE TITLE
excludeGlob is not used when running command directly

### ISSUE THREAD

**Issue by Nxt3** [daidodo/format-imports-vscode#110]
Here is a glob I've attempted to exclude: `"tsImportSorter.configuration.excludeGlob": ["*.spec.*"]`

When running the "Sort Imports" command via the command palette on a file that is excluded, the imports will still be sorted.

![Screenshot 2024-11-05 at 10 30 43 AM](https://github.com/user-attachments/assets/2bcf0280-39fd-4dd2-93ca-0be88945945d)

Expectation: Files that are excluded should never be sorted.

Prettier does this how I'd expect: files in `.prettierignore` are never formatted regardless of how the formatting is invoked.

**Comment by daidodo** [comment]
@Nxt3, thanks for the feedback!

The behaviour is intended for the use case that you want to manually format an excluded file.

Maybe you can provide more details on your use case if you think it's legitimate.

**Comment by daidodo** [comment]
Close the issue as it's expected. Please feel free to reopen should you have any further questions!

**Comment by Nxt3** [comment]
I apologize for the delay, I was on holiday.

I can't seem to reopen the issue but here are more details:

This extension allows us to create a sequence of commands to run when saving a file, [Run commands as code actions](https://marketplace.visualstudio.com/items?itemName=stereokai.vscode-run-commands-as-code-actions).

My sequence looks like this:

```jsonc
  "[typescript]": {
    "editor.codeActionsOnSave": ["source.addMissingImports", "source.runCommandsAsCodeActions.jsTsFormatAndLint"], // add missing imports and then run the below sequence
    "editor.defaultFormatter": "esbenp.prettier-vscode",
    "editor.formatOnSave": false
  },
  "run-commands-as-code-actions.jsTsFormatAndLint": [
    {
      "command": "tsImportSorter.command.sortImports", // format TS imports
      "delay": 150
    },
    {
      "command": "editor.action.formatDocument", // prettier
      "delay": 225
    },
    {
      "command": "eslint.executeAutofix", // eslint
      "delay": 325
    },
    {
      "command": "workbench.action.files.saveWithoutFormatting", // save without formatting
      "delay": 375
    }
  ]
  ```
  
Some spec files I work on have imports that have a dependency on the order:

```typescript
import { patchGlobalConfig } from '@shared';
patchGlobalConfig(); // NOTE: this needs to be called here; if it's placed below these imports, the tests will fail
import { newSpecPage } from '@stencil/core/testing';
import { h } from '@stencil/core';
```

As such, I need to disable formatting imports in these files as TS importer causes a breakage.

In the above code actions sequence, I can verify that if I added a file to the `.prettierignore`, that file will not be formatted. This isn't the case for TS import--it will format the file even if it's ignored.
