### ISSUE TITLE
Does not work .vue files

### ISSUE THREAD

**Issue by JohnLouderback** [daidodo/format-imports-vscode#37]
**Describe the bug**
I can't seem to use this on .vue files

**To Reproduce**
1. Create a .vue single file component
2. include a script block like `<script lang="ts">`
3. Try to sort the imports by save or manual action

**Expected behavior**
It should sort imports in .vue files containing script blocks

**Actual behavior**
It does nothing

**OS (please complete the following information):**

- OS: Windows
- Version: 10

**Comment by daidodo** [comment]
Hi @JohnLouderback,

Thanks for the feedback!

Vue is not supported yet but I've put it in the [TODO list](https://github.com/daidodo/tsimportsorter/blob/master/TODO.md).

**Comment by daidodo** [comment]
@JohnLouderback Please try v7.6.1 which should support *.vue*. Thanks!
