### ISSUE TITLE
Run on save with `editor.codeActionsOnSave`

### ISSUE THREAD

**Issue by brunolm** [daidodo/format-imports-vscode#45]
I'd like to run some other operations on top of sorting imports. It'd be useful if I could use it with `editor.codeActionsOnSave` so I could potentially do something like this:

```
  "editor.codeActionsOnSave": [
    "source.organizeImports",
    "source.fixAll"
  ],
```

**Comment by daidodo** [comment]
@brunolm - Thank you for the suggestion!
Seems there are only a few [code actions supported](https://code.visualstudio.com/docs/languages/javascript#_code-actions-on-save). And I haven't found any examples of how to register a new code action, except [the official API doc](https://code.visualstudio.com/api/references/vscode-api#languages).

I'll come back to it after fixing some bugs. Meanwhile, if you or anyone want to get hands on it, just go ahead and I'll appreciate it.

**Comment by daidodo** [comment]
More links:
https://stackoverflow.com/questions/60718493/difference-between-codeactionsonsave-and-formatonsave-in-vs-code
https://github.com/microsoft/vscode-docs/blob/main/release-notes/v1_41.md#eslint

**Comment by brunolm** [comment]
This extension creates `sources.formatDocument`
https://marketplace.visualstudio.com/items?itemName=rohit-gohri.format-code-action

Maybe it's easy to create something by using it as a reference. I haven't looked into the source code, but assume it should be possible to do it.

**Comment by daidodo** [comment]
@brunolm - I've release v7.3.2 with code action support:

```json
"editor.codeActionsOnSave": ["source.organizeImports.sortImports"]
```

Please check it out and tell me if you have any questions.
Thanks!

**Comment by brunolm** [comment]
It's working! It looks awesome!
Thank you!

**Comment by daidodo** [comment]
@brunolm 
I've release v7.3.4 which fixes the "formatting twice" issue, so you can enable both `autoFormat` and `editor.codeActionsOnSave` now.

**Comment by rshea0** [comment]
The auto format option doesn't appear to be working. I had to use `codeActionsOnSave` to get it to work.

**Comment by daidodo** [comment]
@rshea0 
Could you check if you set:
```
"editor.formatOnSave": false,
```
Other than that, the extension works fine in my end.

If you still have problems, please open an issue.
Thanks!

**Comment by rshea0** [comment]
@daidodo I have `editor.formatOnSave` set to true actually. Maybe it's a conflict with prettier or something? It's fine though, it works with `codeActionsOnSave` (you should mention it in the documentation though, I had to find this thread to find out it was possible).

**Comment by daidodo** [comment]
Ok. If you have prettier then it's possible that prettier runs after the extension and overwrite. That's why I added code action support.
You can find instructions in the "How to use" section.
Thanks!

**Comment by rshea0** [comment]
@daidodo So it looks like even with `codeActionsOnSave` set, it isn't auto sorting in vue files. Other files work fine but vue files don't auto sort (manual sort works). I can open a new issue if you'd like.

**Comment by andrei-zgirvaci** [comment]
@daidodo I actually have the same exact issue as @rshea0. It was working fine in the same project a few days ago, I haven't changed anything... Not sure what's going on.

Tried to run in `debug` mode with `autoFormat ` set to `onSave`, and it does look like it's detecting and formatting, but it doesn't actually change the file. When enabling `codeActionsOnSave` it works perfectly fine!

I am pretty sure it was working fine before the latest extension update on `7.4.12`. This issue seems to be happened a few days ago, just like @rshea0 said.
