### ISSUE TITLE
Flag to disable ESLint checking

### ISSUE THREAD

**Issue by daidodo** [daidodo/format-imports-vscode#47]
Moving [a new feature request](https://github.com/daidodo/format-imports-vscode/issues/44#issuecomment-823689527) to this new issue:

> Is there any interest in adding a flag to disable ESLint checking? We currently use (and love) this tool but the 7.3.0 update broke our setup because the ESLInt config takes precedence over our import-sorter.json.
>
> We use a max-len for our code, but not imports.

> Our ESLint has a max length of 100, but for the import sorter it's 0 (no max at all).
>
> We don't need nicely formatted imports, so we allow unlimited line length just for the imports.
>
> When eslint max-len is set, it breaks that usage pattern since it "overrides" the import-sorter.json.

> Thanks for taking the time to check it out!
>
`.eslintrc`
```json
{
  "env": {
    "es6": true,
    "react-native/react-native": true
  },
  "root": true,
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaFeatures": {
      "jsx": true
    }
  },
  "plugins": [
    "@typescript-eslint",
    "jest",
    "react",
    "react-native",
    "react-hooks"
  ],
  "ignorePatterns": [
    "node_modules",
  ],
  "extends": [
    "eslint:recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:jest/recommended"
  ],
  "rules": {
    "max-len": ["warn", {
      "code": 100,
      "tabWidth": 2,
      "ignoreComments": true,
      "ignoreStrings": true,
      "ignoreTrailingComments": true,
      "ignoreTemplateLiterals": true,
      "ignoreRegExpLiterals": true,
    }],
}
```

`import-sorter.json`
```json
{
  "autoFormat": "onSave",
  "formatExports": false,
  "exclude": ["scripts/", "node_modules"],
  "sortImportsBy": "paths",
  "maxLineLength": 0,
  "bracketSpacing": true,
  "wrappingStyle": {
    "maxBindingNamesPerLine": 0,
    "maxNamesPerWrappedLine": 0,
    "maxDefaultAndBindingNamesPerLine": 0,
    "maxExportNamesPerLine": 0
  },
  "emptyLinesAfterAllImports": 2,
  "groupRules": [
    {
      "regex": "^react(-native)?$"
    },
    {},
    {
      "subGroups": [
        "^@(src|assets|components|constants|context|helpers|hooks|navigation|screens|types|graphql)",
        "^@DATA$",
        "^[.]+",
        "^[.]"
      ]
    }
  ]
}
```

**Comment by dburdan** [comment]
I should've created a new issue in the first place. Thanks again for taking the time to look into this.

**Comment by daidodo** [comment]
May I ask why you disable `formatExports` and what if exports exceed 100 line length?

**Comment by dburdan** [comment]
Just disabled for now as we get formatting implemented each step at a time.

We won't format exports either and will have them at unlimited line length.

**Comment by daidodo** [comment]
Thanks!
Before getting into the solution, I'd like to clarify some options in your *import-sorter.json*:
* `"autoFormat": "onSave"` is unnecessary because it's the default;
* You don't need to add `"node_modules"` in `"exclude"` because it'll be merged to the default, see [here](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/configuration.md#exclude) and [here](https://github.com/daidodo/format-imports/tree/main/docs#default_merger);
* `"sortImportsBy": "paths"` is unnecessary since it's the default;
* `"bracketSpacing": true` is unnecessary since it's the default;

**Comment by dburdan** [comment]
Thanks for the heads up. Even though those are default, I feel it's nice to explicitly list some properties in case the defaults were to change in a future version.

**Comment by daidodo** [comment]
Yes, it's up to you.

Regarding the new feature, my understanding is you want the plugin to ignore `max-len` rule because you've disabled it for imports and exports.

And I also noticed that your *import-sorter.json* has `"emptyLinesAfterAllImports": 2` which can be replaced by ESLint rule [import/newline-after-import](https://github.com/daidodo/format-imports/wiki/ESLint-Compatibility#importnewline-after-import) if you want.

And that brings me to another use case that people might want some rules being ignored while others are in effect.

So my suggestion is as follows:
* Adding an option `ignoreESLintRules: string[] | string` in [Configuration](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/configuration.md).
* [All supported ESLint rules](https://github.com/daidodo/format-imports/wiki/ESLint-Compatibility) will match against **regex**es from the string or items in the array.
* If matched, the rule will be ignored.
* The default value of the option is `[]`, i.e. an empty array.
* [The default merge policy](https://github.com/daidodo/format-imports/tree/main/docs#default_merger) for the option is concatenation, same as [exclude](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/configuration.md#exclude).

Some notes:
* To ignore all ESLint rules, you can just set `ignoreESLintRules: '.*'`.
* To ignore both `indent` and `@typescript-eslint/indent` you can set `ignoreESLintRules: ['indent$']`.
* It's possible that a regex over-matches rules. But given the small number of rules this plugin supports, that shouldn't be a problem.

@dburdan, please tell me your thoughts.
Thanks!

**Comment by dburdan** [comment]
Thanks for the tip on the `emptyLinesAfterAllImports` ESLint rule, we'll definitely use that!

I think your solution above would work perfectly, and also allow room for new use-cases other teams may encounter. That would solve our problems 👍🏼

**Comment by daidodo** [comment]
@dburdan - Sorry for the late response as I was busy recently!
But now the feature is out in v7.4.0!
Please check it out and tell me if you have any questions.

Thanks!

**Comment by dburdan** [comment]
Amazing, thanks so much! I'll give it a try as soon as the update is available.

**Comment by dburdan** [comment]
Upgraded and working 👍🏼  I think it's safe to say this issue can be closed.
