### ISSUE TITLE
Add a groupRule to default options for `node:` prefixed builtin modules

### ISSUE THREAD

**Issue by karlhorky** [daidodo/format-imports-vscode#48]
**Is your feature request related to a problem? Please describe.**

The [new `node:` prefix for module specifiers](https://twitter.com/jasnell/status/1385238402149150721) for builtin / core modules (currently in v16, but will be backported) is not specified in the `groupRules` default configuration, which means that it will be sorted inline around "n".

**Describe the solution you'd like**

Add a group rule at the beginning for module specifiers starting with `node:`

```diff
 "tsImportSorter.configuration.groupRules": [
+  "^node:",
   "^react(-dom)?$",
   "^@angular/",
   "^vue$",
   {},
   "^[@]",
   "^[.]"
 ],
```

**Describe alternatives you've considered**

Adding the group rule at some other position in the list

**Comment by daidodo** [comment]
@karlhorky - Thanks for the feedback!
This is a good feature!
One question: Are `node:` imports BEFORE or AFTER React/Angular/Vue by default?
I'm a bit in favour of AFTER because it's aligned with current behaviour.

Happy to hear your thoughts!

**Comment by karlhorky** [comment]
I guess I don't have strong feelings either way (since it is user-configurable anyway). Usually in my projects, I have Node core modules at the very top.

But as you said, if they are currently below React / Angular / Vue in the current extension configuration, then it would be less of a breaking change to leave them where they are.

**Comment by daidodo** [comment]
@karlhorky - Sorry for the late response!
I've released v7.4.0 to address the issue.
Please have a look and tell me if you have any questions.

Thanks!

**Comment by karlhorky** [comment]
Ah, can you push to GitHub as well? I'll take a look, thanks!

**Comment by daidodo** [comment]
Sure. The main changes are in a [commit](https://github.com/daidodo/format-imports/commit/518fcaaa3b57828cdd3b562cb46c02b84d36fc34) from anonther repo https://github.com/daidodo/format-imports.
