### ISSUE TITLE
Remove semicolons at the end of line in imports

### ISSUE THREAD

**Issue by leobenkel** [daidodo/format-imports-vscode#51]
I would like a setting option to disable trailing semicolons. 

Thank you :)

**Comment by Zielak** [comment]
I don't experience these. Do you have any other tool which would dictate semicolons, like prettier?

**Comment by daidodo** [comment]
@leobenkel 
Have you tried option [hasSemicolon](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/configuration.md#hassemicolon) in config?

**Comment by leobenkel** [comment]
> @leobenkel
> Have you tried option [hasSemicolon](https://github.com/daidodo/format-imports/blob/main/docs/interfaces/configuration.md#hassemicolon) in config?

It says read only so I did not try. I was not sure what path I should be using in the config

**Comment by daidodo** [comment]
Maybe it's a bit misleading.

Basically you can configure the plugin via [a few ways](https://github.com/daidodo/format-imports-vscode#configuration).
For example, you create an *import-sorter.json* file under your project root (same as *package.json*):

```json
{
  "hasSemicolon": false
}
```

Or add an `"importSorter"` section in your *package.json*:

```json
{
  ...
  "importSorter": {
    "hasSemicolon": false
  }
  ...
}
```

**Comment by leobenkel** [comment]
oh that works ! Thanks ! 🎉

**Comment by leobenkel** [comment]
Can I set this settings on the vscode level rather than per project ?

**Comment by daidodo** [comment]
Yes, you're right!

**Comment by leobenkel** [comment]
> Yes, you're right!

I removed the `importSorter` setting from my `package.json` and add it in the global `settings.json` with the line above and that did not work. The line in the `settings.json` is grayed out, not sure what that mean

**Comment by leobenkel** [comment]
lol don't mind me. I'm stupid xD 

In my line above, I put `hasSemicolor` instead of `hasSemicolon` .... 🤦‍♂️
