### ISSUE TITLE
How to set extension respect prettier wrap style?

### ISSUE THREAD

**Issue by tjx666** [daidodo/format-imports-vscode#52]
**Describe the bug**

I use prettier to format my code, but It often happens that prettier format the code after this extension modify code. In face, I think the wrap style should be prettier's responsibility.

**Comment by daidodo** [comment]
Thanks for the feedback!

You can set `"wrappingStyle": "prettier"` if you prefer Prettier's style.
More details can be found in the wiki: [Line-Wrapping-Style](https://github.com/daidodo/format-imports/wiki/Line-Wrapping-Style).

**Comment by tjx666** [comment]
Fine, thanks
