### ISSUE TITLE
extension startup time is so long

### ISSUE THREAD

**Issue by tjx666** [daidodo/format-imports-vscode#53]
I think there should not be so much log after publish the extension. The startup time costs so long may be also related to this?

![image](https://user-images.githubusercontent.com/41773861/123798085-6f523380-d919-11eb-8c12-e734f2d7b76e.png)

**Comment by daidodo** [comment]
Thanks for the feedback!

Unfortunately I don't have much time recently. So if you or someone could help with the issue, I'd be very grateful!

**Comment by tjx666** [comment]
If I have time, I may help to fix it.

**Comment by tjx666** [comment]
@daidodo @zddai

module format-imports import costs too long,


![image](https://user-images.githubusercontent.com/41773861/148378190-7b8b6d21-3356-4773-8e03-2b18de8a7615.png)

**Comment by daidodo** [comment]
Thanks for the sharing!

This reminds me a previous attempt to webpack the plugin which failed due to eslint loading issues: https://github.com/eslint/eslint/issues/13974.

Currently, I'm on something else but happy to suggest if you're interested.

**Comment by tjx666** [comment]
@daidodo fixed in https://github.com/daidodo/format-imports-vscode/pull/64

**Comment by daidodo** [comment]
@tjx666 
Sorry for the late response!
I believe there is an improvement from the new release v7.4.13 after I webpacked the extension.

<img width="380" alt="image" src="https://user-images.githubusercontent.com/8170176/161160182-8666ec71-82e3-469d-93a2-6eaf2ce179f1.png">

It was quite a journey to make a solution from:
* https://github.com/eslint/eslint/issues/15575
* https://github.com/eslint/eslint/issues/13974
* https://github.com/daidodo/format-imports/commit/c54d27de5509b008832cf9436b8f0a98f37f7114

Please have a try and tell me if you have any questions.
Thanks!

**Comment by tjx666** [comment]
![Uploading image.png…]()

**Comment by tjx666** [comment]
Much better than before @daidodo
