### ISSUE TITLE
Exception: Unexpected token < in JSON at position 37

### ISSUE THREAD

**Issue by jenshaw86** [daidodo/format-imports-vscode#54]
## Code snippet triggering the exception

```ts
// INSERT CODE HERE
```

## All Logs

(Please open the output channel for "JS/TS Import/Export Sorter" and copy/paste ALL logs here)

```log
PASTE LOGS HERE
```

**Comment by daidodo** [comment]
Hi @jenshaw86 , could you share the code or config causing the exception? As well as plugin logs when it's happening. Thanks!
