### ISSUE TITLE
Format entire folder, nested folders or even entire projects

### ISSUE THREAD

**Issue by mikededo** [daidodo/format-imports-vscode#57]
**Is your feature request related to a problem? Please describe.**
Actually, no, it is something it would be pretty useful to have.

**Describe the solution you'd like**
Basically it could be done in many ways, but probably, the easiest would be by right clicking in the files side bar. It would show the options of sorting import/exports of all the files that are inside a folder. With this, it would not be necessary to run the extension file by file.

**Describe alternatives you've considered**
None, but it could work similarly when running `eslint` on a project from the terminal.

**Additional context**
None.

**Comment by daidodo** [comment]
Thanks for the feedback!

This is available via CLI: https://github.com/daidodo/format-imports#format-a-directory
