### ISSUE TITLE
Add support for type modifiers on import names

### ISSUE THREAD

**Issue by dicarlo2** [daidodo/format-imports-vscode#61]
**Is your feature request related to a problem? Please describe.**
https://devblogs.microsoft.com/typescript/announcing-typescript-4-5/#type-on-import-names

**Describe the solution you'd like**
Support for at least preserving type modifiers on import names.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by daidodo** [comment]
@dicarlo2 
Thanks for the feedback!

I've published [v7.4.2](https://marketplace.visualstudio.com/items?itemName=dozerg.tsimportsorter) to address the issue. Please have a look.
