### ISSUE TITLE
Exception: Unexpected token } in JSON at position 777

### ISSUE THREAD

**Issue by binaryjack** [daidodo/format-imports-vscode#65]
## Code snippet triggering the exception

```ts
// INSERT CODE HERE
```

## All Logs

(Please open the output channel for "JS/TS Import/Export Sorter" and copy/paste ALL logs here)

```log
PASTE LOGS HERE
```

**Comment by daidodo** [comment]
Hi, could you share your package.json or import-sorter.json? Thanks!

**Comment by daidodo** [comment]
@binaryjack 
I will close this if there is no more activity.
Please feel free to re-open it if you have more info.
Thanks!
