### ISSUE TITLE
Autoformat is not working on save (vs code 1.65.2, extension v7.4.12)

### ISSUE THREAD

**Issue by fedulovivan** [daidodo/format-imports-vscode#66]
Noticed that after recent update of vscode and/or(?) extension there is a problem with triggering autoformat upon saving file.
(!) Note that formatting is working as expected if triggered manualy (Cmd + Shift + P -> Sort Imports/Exports)

**Comment by mkholt** [comment]
I am seeing the exact same behaviour.
Tried adding the autoFormat setting to settings.json manually, that has no effect.
Works fine on manual triggering of the extension.

**Comment by daidodo** [comment]
Thanks for the feedback!

Hopefully it should be fixed in v7.4.13.
Please tell me if you still have issues.

**Comment by mkholt** [comment]
Can confirm that it now auto-formats on save after updating to 7.4.13
