### ISSUE TITLE
Problems loading reference 'file:///Users/xxx/import-sorter.schema.json'

### ISSUE THREAD

**Issue by tjx666** [daidodo/format-imports-vscode#69]
**Describe the bug**

Open any project contains package.json, show the error message in screenshot

**Screenshots**

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/41773861/161562323-357b13db-cda7-4ce5-a6ae-53a39b45bf55.png">

**OS (please complete the following information):**

- OS: MacOS 12.3.1
- VSCode: 1.67.0-insider
- format-imports-vscode: v7.4.14

**Comment by daidodo** [comment]
Thanks for the feedback!

Please try v7.4.15 and tell me if the issue persists.
