### ISSUE TITLE
give use more meaningful error message when parse package.json error

### ISSUE THREAD

**Issue by tjx666** [daidodo/format-imports-vscode#76]
Notify user parsing package.json parrse error would be more useful. Maybe we need https://github.com/daidodo/format-imports throw error with error code to identify the exception reason.

When I have merge conflicts in package.json:

@daidodo

![image](https://user-images.githubusercontent.com/41773861/184108091-c9adf5ef-3faf-4749-8e97-c513e53aa3e0.png)

**Comment by tjx666** [comment]
Or provide user a setting to disable error message. Just log the error message to output channel.
@daidodo

**Comment by daidodo** [comment]
Thanks for the feedback!

I've suppressed package JSON parsing error in v7.4.20.
