### ISSUE TITLE
Exception: Unexpected token / in JSON at position 90

### ISSUE THREAD

**Issue by anshul-gauba-30067469** [daidodo/format-imports-vscode#80]
## Code snippet triggering the exception

```ts
// INSERT CODE HERE
```

## All Logs

(Please open the output channel for "JS/TS Import/Export Sorter" and copy/paste ALL logs here)

```log
PASTE LOGS HERE
```

**Comment by daidodo** [comment]
@anshul-gauba-30067469 
Thanks for the feedback!

Could you share more details about the issue, e.g. *import-sorter.json*, [debug logs](https://github.com/daidodo/format-imports-vscode/blob/master/CONTRIBUTING.md#debug-mode), etc?
