### ISSUE TITLE
Exception: EMFILE: too many open files, open 'c:\project\ffbd-admin\package.json'

### ISSUE THREAD

**Issue by farjana74** [daidodo/format-imports-vscode#81]
## Code snippet triggering the exception

```ts
// INSERT CODE HERE
```

## All Logs

(Please open the output channel for "JS/TS Import/Export Sorter" and copy/paste ALL logs here)

```log
PASTE LOGS HERE
```

**Comment by daidodo** [comment]
Thanks for the feedback!

Could you share more details about the issue for me to investigate?
