### ISSUE TITLE
Add VS Code extension URL to GitHub repo About section

### ISSUE THREAD

**Issue by karlhorky** [daidodo/format-imports-vscode#82]
**Is your feature request related to a problem? Please describe.**

It would be great to have a link to [the VS Code extension](https://marketplace.visualstudio.com/items?itemName=dozerg.tsimportsorter) in the **About** section of this repo (can be added by clicking on the gear icon):

![Screenshot 2022-10-27 at 19 07 58](https://user-images.githubusercontent.com/1935696/198354855-179c4dc7-7192-448c-ad7e-aaaf2c614c58.png)

**Describe the solution you'd like**

Already described above.

**Describe alternatives you've considered**

--

**Additional context**

--

**Comment by daidodo** [comment]
Thanks for the feedback!

Done!

**Comment by karlhorky** [comment]
Great, thanks!
