### ISSUE TITLE
satisfies operator bug

### ISSUE THREAD

**Issue by okitan** [daidodo/format-imports-vscode#86]
**Describe the bug**
When I use `satisfies` operator  intruduced in Typescript 4.9.
JS/TS Import/Export Sorter removes lines I actually used.

**To Reproduce**

Given:
`a.ts`

```a.ts
export type Hoge = {
  a: string;
};
```

`b.ts`
```b.ts
export const Fuga: string = "fuga";
```

When:
JS/TS Import/Export Sorter formater runs against `c.ts`.

```c.ts
import { Hoge } from './a';
import { Fuga } from './b';

export const schema = { a: Fuga } satisfies Hoge;
````

**Expected behavior**
It should remain as is.

**Actual behavior**
It removes `import { Fuga } from './b';`

**OS (please complete the following information):**

- OS:Mac OS
- Version: v7.5.2

**VS Code (please complete the following information):**

- Version: 1.73.1

**Comment by daidodo** [comment]
Sorry for the late response!

I think it's a bug in TS 4.9.3 that it thinks `Fuga` is unused.
I updated to TS 4.9.4 and it works fine.

**Comment by daidodo** [comment]
Please try [v7.5.3](https://marketplace.visualstudio.com/items?itemName=dozerg.tsimportsorter).
