### ISSUE TITLE
Sort unassigned imports inline with assigned

### ISSUE THREAD

**Issue by acroyear** [daidodo/format-imports-vscode#97]
I may have the wrong vocabulary, but my problem is this

I have
```
import { useState, useEffect, useCallback, useMemo, useRef } from 'preact/hooks';
import 'ojs/ojcheckboxset';
import { ojCheckboxset } from 'ojs/ojcheckboxset';
import { ExtendGlobalProps, PropertyChanged } from 'ojs/ojvcomponent';
import { h, RenderableProps, JSX } from 'preact';
```

applying my groups, I get
```
import 'ojs/ojcheckboxset';
import { JSX, RenderableProps, h } from 'preact';
import { useCallback, useMemo } from 'preact/hooks';
import { ExtendGlobalProps, PropertyChanged } from 'ojs/ojvcomponent';
import { ojCheckboxset } from 'ojs/ojcheckboxset';
```

what I want is for that top item to be inline with the rest of ojs entries
```
import { JSX, RenderableProps, h } from 'preact';
import { useCallback, useMemo } from 'preact/hooks';
import { ExtendGlobalProps, PropertyChanged } from 'ojs/ojvcomponent';
import 'ojs/ojcheckboxset';
import { ojCheckboxset } from 'ojs/ojcheckboxset';
```

Is there a setting to make this possible?

**Comment by acroyear** [comment]
Unassigned imports are ignored, as the order they are imported in may be important.

from eslint-plugin-import/order

that's the word, Unassigned. In our case, the order doesn't matter so we'd like them inline with their assigned imports.

**Comment by daidodo** [comment]
Sorry for the late response!

Please refer to https://github.com/daidodo/format-imports/wiki/Grouping-Rules.
I think you might need a group for all ojs imports (`flags: "all"`), and define its order among other groups.

**Comment by acroyear** [comment]
that got it (sorry, hadn't looked at that inbox in a while). thank you.
