### ISSUE TITLE
Add ability to disable completly line wrapping.

### ISSUE THREAD

**Issue by l0ner** [daidodo/format-imports-vscode#98]
The thing is simple: i don't want my imports to be split on several lines. I have disabled all the options for splitting of the imports, but the ones on very long lines still get split if they exceed 80 characters.

I have 120 set as the word wrapping column in VSCode and i have disabled the max-len rule in eslint.

**Comment by daidodo** [comment]
Please read the wiki: https://github.com/daidodo/format-imports/wiki/Line-Wrapping-Style.

And tell me if you still have questions. Thanks!

**Comment by l0ner** [comment]
Thanks. Somehow `maxLineLength` has eluded me when I've read it in may.
